

import fill_database

# Eerst ruimtes genereren
fill_database.new_ruimte(1, 'Fietsenstalling')
fill_database.new_ruimte(2, 'Server ruimte')
fill_database.new_ruimte(3, 'Medischeinen hok')
fill_database.new_ruimte(4, 'Kroeg')
fill_database.new_ruimte(5, 'Slaapkamer')

# Deze doen per persoon
persoons_id = fill_database.new_person('Ralph', 'van Leeuwen', 1, 1)
fill_database.new_tag(6666, 1, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 1)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 1)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 1)

persoons_id = fill_database.new_person('Sven', 'Visser', 1, 0)
fill_database.new_tag(1111, 0, 1, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 1)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 1)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Cornelis', 'Stuurman', 0, 1)
fill_database.new_tag(2222, 1, 1, persoons_id)
fill_database.new_toegang(persoons_id, 1, 1)
fill_database.new_toegang(persoons_id, 2, 1)
fill_database.new_toegang(persoons_id, 3, 1)
fill_database.new_toegang(persoons_id, 4, 1)
fill_database.new_toegang(persoons_id, 5, 1)

persoons_id = fill_database.new_person('Ruben', 'van der Weide', 0, 0)
fill_database.new_tag(3333, 0, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Marcel', 'Haazen', 1, 1)
fill_database.new_tag(4444, 1, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 1)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 1)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 1)

persoons_id = fill_database.new_person('Piet', 'Puk', 1, 0)
fill_database.new_tag(5555, 0, 1, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 1)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 1)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Abdulah', 'Adelhavic', 0, 1)
fill_database.new_tag(7777, 1, 1, persoons_id)
fill_database.new_toegang(persoons_id, 1, 1)
fill_database.new_toegang(persoons_id, 2, 1)
fill_database.new_toegang(persoons_id, 3, 1)
fill_database.new_toegang(persoons_id, 4, 1)
fill_database.new_toegang(persoons_id, 5, 1)

persoons_id = fill_database.new_person('Doerak', 'Vermeulen', 0, 0)
fill_database.new_tag(8888, 0, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Lonely', 'Planet', 1, 1)
fill_database.new_tag(9999, 1, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 1)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 1)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 1)

persoons_id = fill_database.new_person('Tony', 'Wheeler', 1, 0)
fill_database.new_tag(1000, 0, 1, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 1)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 1)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Herman', 'Brom', 0, 1)
fill_database.new_tag(1001, 1, 1, persoons_id)
fill_database.new_toegang(persoons_id, 1, 1)
fill_database.new_toegang(persoons_id, 2, 1)
fill_database.new_toegang(persoons_id, 3, 1)
fill_database.new_toegang(persoons_id, 4, 1)
fill_database.new_toegang(persoons_id, 5, 1)

persoons_id = fill_database.new_person('Gijs', 'Schouten', 0, 0)
fill_database.new_tag(1002, 0, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Toby', 'Visser', 1, 1)
fill_database.new_tag(1003, 1, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 1)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 1)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 1)

persoons_id = fill_database.new_person('Doerak', 'Visser', 1, 0)
fill_database.new_tag(1004, 0, 1, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 1)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 1)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Bill', 'Gates', 0, 1)
fill_database.new_tag(1005, 1, 1, persoons_id)
fill_database.new_toegang(persoons_id, 1, 1)
fill_database.new_toegang(persoons_id, 2, 1)
fill_database.new_toegang(persoons_id, 3, 1)
fill_database.new_toegang(persoons_id, 4, 1)
fill_database.new_toegang(persoons_id, 5, 1)

persoons_id = fill_database.new_person('Paul', 'Allen', 0, 0)
fill_database.new_tag(1006, 0, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Satya', 'Nadella', 1, 1)
fill_database.new_tag(1007, 1, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 1)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 1)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 1)

persoons_id = fill_database.new_person('Qing', 'Gu', 1, 0)
fill_database.new_tag(1008, 0, 1, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 1)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 1)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Steve', 'Jobs', 0, 1)
fill_database.new_tag(1009, 1, 1, persoons_id)
fill_database.new_toegang(persoons_id, 1, 1)
fill_database.new_toegang(persoons_id, 2, 1)
fill_database.new_toegang(persoons_id, 3, 1)
fill_database.new_toegang(persoons_id, 4, 1)
fill_database.new_toegang(persoons_id, 5, 1)

persoons_id = fill_database.new_person('Barack', 'Obama', 0, 0)
fill_database.new_tag(1010, 0, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Donald', 'Trump', 1, 1)
fill_database.new_tag(1011, 1, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 1)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 1)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 1)

persoons_id = fill_database.new_person('David', 'Cameron', 1, 0)
fill_database.new_tag(1012, 0, 1, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 1)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 1)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Willem', 'van Oranje', 0, 1)
fill_database.new_tag(1013, 1, 1, persoons_id)
fill_database.new_toegang(persoons_id, 1, 1)
fill_database.new_toegang(persoons_id, 2, 1)
fill_database.new_toegang(persoons_id, 3, 1)
fill_database.new_toegang(persoons_id, 4, 1)
fill_database.new_toegang(persoons_id, 5, 1)

persoons_id = fill_database.new_person('Strijk', 'Bout', 0, 0)
fill_database.new_tag(1014, 0, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Franklin', 'Rooseveld', 1, 1)
fill_database.new_tag(1015, 1, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 1)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 1)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 1)

persoons_id = fill_database.new_person('Harry', 'Truman', 1, 0)
fill_database.new_tag(1016, 0, 1, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 1)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 1)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Dwight', 'Eisenhower', 0, 1)
fill_database.new_tag(1017, 1, 1, persoons_id)
fill_database.new_toegang(persoons_id, 1, 1)
fill_database.new_toegang(persoons_id, 2, 1)
fill_database.new_toegang(persoons_id, 3, 1)
fill_database.new_toegang(persoons_id, 4, 1)
fill_database.new_toegang(persoons_id, 5, 1)

persoons_id = fill_database.new_person('John', 'Kennedy', 0, 0)
fill_database.new_tag(1018, 0, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Lyndon', 'Johnson', 1, 1)
fill_database.new_tag(1019, 1, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 1)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 1)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 1)

persoons_id = fill_database.new_person('Richard', 'Nixon', 1, 0)
fill_database.new_tag(1020, 0, 1, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 1)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 1)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Regald', 'Ford', 0, 1)
fill_database.new_tag(1021, 1, 1, persoons_id)
fill_database.new_toegang(persoons_id, 1, 1)
fill_database.new_toegang(persoons_id, 2, 1)
fill_database.new_toegang(persoons_id, 3, 1)
fill_database.new_toegang(persoons_id, 4, 1)
fill_database.new_toegang(persoons_id, 5, 1)

persoons_id = fill_database.new_person('James', 'Carter', 0, 0)
fill_database.new_tag(1022, 0, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Ronald', 'Reagan', 1, 1)
fill_database.new_tag(1023, 1, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 1)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 1)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 1)

persoons_id = fill_database.new_person('George', 'Bush', 1, 0)
fill_database.new_tag(1024, 0, 1, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 1)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 1)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('William', 'Clinton', 0, 1)
fill_database.new_tag(1025, 1, 1, persoons_id)
fill_database.new_toegang(persoons_id, 1, 1)
fill_database.new_toegang(persoons_id, 2, 1)
fill_database.new_toegang(persoons_id, 3, 1)
fill_database.new_toegang(persoons_id, 4, 1)
fill_database.new_toegang(persoons_id, 5, 1)

persoons_id = fill_database.new_person('George W', 'Bush', 0, 0)
fill_database.new_tag(1026, 0, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('George', 'Washinton', 1, 1)
fill_database.new_tag(1027, 1, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 1)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 1)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 1)

persoons_id = fill_database.new_person('John', 'Adams', 1, 0)
fill_database.new_tag(1028, 0, 1, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 1)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 1)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Thomas', 'Jefferson', 0, 1)
fill_database.new_tag(1029, 1, 1, persoons_id)
fill_database.new_toegang(persoons_id, 1, 1)
fill_database.new_toegang(persoons_id, 2, 1)
fill_database.new_toegang(persoons_id, 3, 1)
fill_database.new_toegang(persoons_id, 4, 1)
fill_database.new_toegang(persoons_id, 5, 1)

persoons_id = fill_database.new_person('James', 'Maddison', 0, 0)
fill_database.new_tag(1030, 0, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('James', 'Monroe', 1, 1)
fill_database.new_tag(1031, 1, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 1)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 1)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 1)

persoons_id = fill_database.new_person('John Q', 'Adams', 1, 0)
fill_database.new_tag(1032, 0, 1, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 1)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 1)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Andrew', 'Jackson', 0, 1)
fill_database.new_tag(1033, 1, 1, persoons_id)
fill_database.new_toegang(persoons_id, 1, 1)
fill_database.new_toegang(persoons_id, 2, 1)
fill_database.new_toegang(persoons_id, 3, 1)
fill_database.new_toegang(persoons_id, 4, 1)
fill_database.new_toegang(persoons_id, 5, 1)

persoons_id = fill_database.new_person('Martin', 'van Buuren', 0, 0)
fill_database.new_tag(1034, 0, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('William', 'Harrison', 1, 1)
fill_database.new_tag(1035, 1, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 1)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 1)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 1)

persoons_id = fill_database.new_person('John', 'Taylor', 1, 0)
fill_database.new_tag(1036, 0, 1, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 1)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 1)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('James', 'Polk', 0, 1)
fill_database.new_tag(1037, 1, 1, persoons_id)
fill_database.new_toegang(persoons_id, 1, 1)
fill_database.new_toegang(persoons_id, 2, 1)
fill_database.new_toegang(persoons_id, 3, 1)
fill_database.new_toegang(persoons_id, 4, 1)
fill_database.new_toegang(persoons_id, 5, 1)

persoons_id = fill_database.new_person('Zachary', 'Taylor', 0, 0)
fill_database.new_tag(1038, 0, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Millard', 'Fillmore', 0, 0)
fill_database.new_tag(1039, 0, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Franklin', 'Pierce', 0, 0)
fill_database.new_tag(1040, 0, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('James', 'Buchanan', 0, 0)
fill_database.new_tag(1041, 0, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Abraham', 'Lincoln', 0, 0)
fill_database.new_tag(1042, 0, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Andrew', 'Johnson', 0, 0)
fill_database.new_tag(1043, 0, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Ullysses', 'Grant', 0, 0)
fill_database.new_tag(1044, 0, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Rutherford', 'Hayes', 0, 0)
fill_database.new_tag(1045, 0, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('James', 'Garfield', 0, 0)
fill_database.new_tag(1046, 0, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Chester', 'Arthur', 0, 0)
fill_database.new_tag(1047, 0, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Steven', 'Cleveland', 0, 0)
fill_database.new_tag(1048, 0, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Benjamin', 'Harrison', 0, 0)
fill_database.new_tag(1049, 0, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Steven G', 'Cleveland', 0, 0)
fill_database.new_tag(1050, 0, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('William', 'McKinley', 0, 0)
fill_database.new_tag(1051, 0, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Theodore', 'Roosevelt', 0, 0)
fill_database.new_tag(1052, 0, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('William', 'Taft', 0, 0)
fill_database.new_tag(1053, 0, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Thomas', 'Wilson', 0, 0)
fill_database.new_tag(1054, 0, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Warren', 'Harding', 0, 0)
fill_database.new_tag(1055, 0, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('John', 'Coolidge', 0, 0)
fill_database.new_tag(1056, 0, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Herbert', 'Hoover', 0, 0)
fill_database.new_tag(1057, 0, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Max', 'Verstappen', 0, 0)
fill_database.new_tag(1058, 0, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Karel', 'Doorman', 0, 0)
fill_database.new_tag(1059, 0, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 0)

persoons_id = fill_database.new_person('Michiel', 'de Ruyter', 0, 0)
fill_database.new_tag(1060, 0, 0, persoons_id)
fill_database.new_toegang(persoons_id, 1, 0)
fill_database.new_toegang(persoons_id, 2, 0)
fill_database.new_toegang(persoons_id, 3, 0)
fill_database.new_toegang(persoons_id, 4, 0)
fill_database.new_toegang(persoons_id, 5, 0)